"""empty message

Revision ID: c760264843d1
Revises: 
Create Date: 2019-06-18 17:21:26.000941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c760264843d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='picture')
    op.drop_table('picture')
    op.drop_table('foodpic')
    op.drop_table('picturepic')
    op.drop_index('id', table_name='food')
    op.drop_table('food')
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    op.drop_table('foodcontent')
    op.drop_table('picturecontent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picturecontent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('picture_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], name='picturecontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('foodcontent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('food_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='foodcontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('food',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('food_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('food_title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('food_desc', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('food_abstract', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('food_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'food', ['id'], unique=True)
    op.create_table('picturepic',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pic_url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('picture_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], name='picturepic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('foodpic',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pic_url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('food_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='foodpic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('picture',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('pic_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pic_title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pic_abstract', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pic_desc', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pic_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'picture', ['id'], unique=True)
    # ### end Alembic commands ###
