"""empty message

Revision ID: 01291adef59b
Revises: bdf85c99b59d
Create Date: 2019-05-12 13:13:12.642993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01291adef59b'
down_revision = 'bdf85c99b59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='food')
    op.drop_table('food')
    op.drop_table('foodcontent')
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    op.drop_table('foodpic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodpic',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pic_url', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('food_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='foodpic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('foodcontent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('food_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='foodcontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('food',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('food_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('food_title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('food_desc', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'food', ['id'], unique=True)
    # ### end Alembic commands ###
